apiVersion: apps/v1
kind: Deployment  
metadata:
  name: portfolio-blazor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: portfolio-blazor
  template:
    metadata:
      labels:
        app: portfolio-blazor
      spec:
        containers:
          - name: portfolio-blazor
            image: IMAGEM_AQUI
            ports:
              - containerPort: 8080